# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

---
trigger:
  - master

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

resources:
  containers:
    - container: mongo
      image: mongo

strategy:
  matrix:
    linux:
      imageName: "ubuntu-18.04"
    windows:
      imageName: "windows-latest"
  maxParallel: 1

pool:
  vmImage: $(imageName)

steps:
  - task: DotNetCoreCLI@1
    command: 'restore'

  - task: DotNetCoreCLI@2
    command: 'build'

  - task: DotNetCoreCLI@3
    command: 'test'
    variables:
      APPSETTINGS_FILENAME: appsettings.Integration.json

  - task: DotNetCoreCLI@3
    command: 'publish'
    outputDir: MorphicServer
