# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

---
trigger:
  - master

resources:
  containers:
    - container: mongo
      image: mongo
      ports:
        - 27017:27017

pool:
  vmImage: "ubuntu-18.04"

stages:
  - stage: BuildEnv
    jobs:
      - job: BuildEnv
        steps:
          - task: Docker@2
            displayName: Build stage 1
            inputs:
              command: 'build'
              Dockerfile: Dockerfile
              buildContext: .
              arguments: --target build-env --tag MorphicLiteServerBuildEnv:$(Build.BuildNumber)
          - task: CmdLine@2
            inputs:
              script: 'docker run MorphicLiteServerBuildEnv:$(Build.BuildNumber) --entrypoint "dotnet test"
          - task: Docker@2
            displayName: Build stage 2
            inputs:
              command: 'buildAndPush'
              Dockerfile: Dockerfile
              buildContext: .
              containerRegistry: oregondesignservices/MorphicLiteServerBuildEnv
              tags: |
                $(Build.BuildNumber)
