# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

---
trigger:
  - master

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

resources:
  containers:
    - container: mongo
      image: mongo

strategy:
  matrix:
    linux:
      imageName: "ubuntu-18.04"
    windows:
      imageName: "windows-latest"
  maxParallel: 1

pool:
  vmImage: $(imageName)

stages:
  - stage: Build
    jobs:
      - job: Restore
        steps:
          - task: DotNetCoreCLI@1
            inputs:
              command: 'restore'

      - job: Build
        steps:
          - task: DotNetCoreCLI@2
            inputs:
              command: 'build'

  - stage: Test
    jobs:
      - job: Test
        variables:
          APPSETTINGS_FILENAME: appsettings.Integration.json
        steps:
          - task: DotNetCoreCLI@3
            inputs:
              command: 'test'

  - stage: Publish
    jobs:
      - job: Publish
        steps:
          - task: DotNetCoreCLI@3
            inputs:
              command: 'publish'
              outputDir: MorphicServer
