# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

---
trigger:
  - master

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

resources:
  containers:
    - container: mongo
      image: mongo
      ports: 27017

pool:
  vmImage: "ubuntu-18.04"

stages:
  - stage: Build
    jobs:
      - job: Build
        variables:
          APPSETTINGS_FILENAME: appsettings.Integration.json
        steps:
          - task: DotNetCoreCLI@2
            displayName: Restore
            inputs:
              command: 'restore'
          - task: DotNetCoreCLI@2
            displayName: Build
            inputs:
              command: 'build'
          - task: DotNetCoreCLI@2
            displayName: Test
            inputs:
              command: 'test'
          - task: DotNetCoreCLI@2
            displayName: Publish
            inputs:
              command: 'publish'
              outputDir: MorphicServer
