# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

---
trigger:
  branches:
    include:
      - master
      - develop
      - "release/*"
      - "hotfix/*"
  tags:
    - "v*"


variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  imageName: 'morphiclite'

resources:
  containers:
    - container: mongo
      image: mongo
      ports:
        - 27017:27017

pool:
  vmImage: "ubuntu-18.04"

stages:
  - stage: Build
    jobs:
      - job: Build
        services:
          mongo: mongo
        steps:
          - task: DotNetCoreCLI@2
            displayName: Restore
            inputs:
              command: 'restore'
          - task: DotNetCoreCLI@2
            displayName: Build
            inputs:
              command: 'build'
          - task: DotNetCoreCLI@2
            displayName: Test
            inputs:
              command: 'test'
          - task: DotNetCoreCLI@2
            displayName: Publish
            inputs:
              command: 'publish'
              outputDir: MorphicServer
  - stage: docker
    jobs:
      - job: build_and_publish_image
        condition: or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Build.SourceBranch'], 'refs/heads/develop'), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
        steps: 
          - task: Docker@2
            displayName: Login to docker hub
            inputs:
              command: login
              containerRegistry: morphicworld dockerhub
          - task: Docker@2
            displayName: build and push image
            inputs:
              repository: morphicworld/morphiclite
              command: buildAndPush
              Dockerfile: Dockerfile
              tags: |
                latest
