# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

---
trigger:
  - master

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  imageName: 'morphiclite'

resources:
  containers:
    - container: mongo
      image: mongo
      ports:
        - 27017:27017

pool:
  vmImage: "ubuntu-18.04"

stages:
  - stage: Build
    jobs:
      - job: Build
        services:
          mongo: mongo
        steps:
          - task: DotNetCoreCLI@2
            displayName: Restore
            inputs:
              command: 'restore'
          - task: DotNetCoreCLI@2
            displayName: Build
            inputs:
              command: 'build'
          - task: DotNetCoreCLI@2
            displayName: Test
            inputs:
              command: 'test'
          - task: DotNetCoreCLI@2
            displayName: Publish
            inputs:
              command: 'publish'
              outputDir: MorphicServer
  - stage: build and publish docker image
    jobs:
      - job: build_and_publis_image
        steps: 
          - task: Docker@2
            displayName: Build an image
            inputs:
              containerRegistry: morphicworld dockerhub
              repository: morphiclite
              command: build
              Dockerfile: Dockerfile
          - task: Docker@2
            displayName: Push image
            inputs:
              containerRegistry: morphicworld dockerhub
              repository: morphiclite
              command: push
              tags: |
                latest
