# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

---
trigger:
  - master

resources:
  containers:
    - container: mongo
      image: mongo
      ports:
        - 27017:27017

pool:
  vmImage: "ubuntu-18.04"

stages:
  - stage: Build
    jobs:
      - job: Build
        services:
          mongo: mongo
        steps:
          - task: Docker@2
            displayName: Build stage 1
            inputs:
              command: 'build'
              Dockerfile: Dockerfile
              buildContext: .
              arguments: --target build-env
              tags: |
                $(Build.BuildNumber)
                build-env
          - task: Docker@2
            displayName: Build stage 2
            inputs:
              command: 'build'
              Dockerfile: Dockerfile
              buildContext: .
              tags: |
                $(Build.BuildNumber)
