# Copyright 2020 Raising the Floor - International
#
# Licensed under the New BSD license. You may not use this file except in
# compliance with this License.
#
# You may obtain a copy of the License at
# https://github.com/GPII/universal/blob/master/LICENSE.txt
#
# The R&D leading to these results received funding from the:
# * Rehabilitation Services Administration, US Dept. of Education under
#   grant H421A150006 (APCP)
# * National Institute on Disability, Independent Living, and
#   Rehabilitation Research (NIDILRR)
# * Administration for Independent Living & Dept. of Education under grants
#   H133E080022 (RERC-IT) and H133E130028/90RE5003-01-00 (UIITA-RERC)
# * European Union's Seventh Framework Programme (FP7/2007-2013) grant
#   agreement nos. 289016 (Cloud4all) and 610510 (Prosperity4All)
# * William and Flora Hewlett Foundation
# * Ontario Ministry of Research and Innovation
# * Canadian Foundation for Innovation
# * Adobe Foundation
# * Consumer Electronics Association Foundation

# How to run the supporting services for MorphicServer:
#
# $ docker-compose -f docker-compose.integ-test.yml up

version: "3.7"
services:
  mongo:
    image: mongo

  morphicserver:
    hostname: morphicserver
    entrypoint: dotnet test 
    depends_on:
      - mongo
    build:
      context: .
      target: build-env
    ports:
      - "5002:80"
    environment:
      APPSETTINGS_FILENAME: appsettings.Integration.json
