# Copyright 2020 Raising the Floor - International
#
# Licensed under the New BSD license. You may not use this file except in
# compliance with this License.
#
# You may obtain a copy of the License at
# https://github.com/GPII/universal/blob/master/LICENSE.txt
#
# The R&D leading to these results received funding from the:
# * Rehabilitation Services Administration, US Dept. of Education under
#   grant H421A150006 (APCP)
# * National Institute on Disability, Independent Living, and
#   Rehabilitation Research (NIDILRR)
# * Administration for Independent Living & Dept. of Education under grants
#   H133E080022 (RERC-IT) and H133E130028/90RE5003-01-00 (UIITA-RERC)
# * European Union's Seventh Framework Programme (FP7/2007-2013) grant
#   agreement nos. 289016 (Cloud4all) and 610510 (Prosperity4All)
# * William and Flora Hewlett Foundation
# * Ontario Ministry of Research and Innovation
# * Canadian Foundation for Innovation
# * Adobe Foundation
# * Consumer Electronics Association Foundation

# How to run the supporting services for MorphicServer:
#
# $ docker swarm init    (only needed the first time)
# $ docker stack deploy -c docker-compose.dev.yaml morphic-server
#
# How to shut down the supporting services:
# $ docker stack rm morphic-server

version: "3.7"
services:
  morphicserver:
    hostname: morphicserver
    depends_on:
      - mongo
    build:
      context: .
    ports:
      - "5002:80"
    environment:
      DATABASESETTINGS__CONNECTIONSTRING:  "mongodb://mongo:27017"
      DATABASESETTINGS__DATABASENAME:      "Morphic"
      ASPNETCORE_ENVIRONMENT:              "Production"
      SERILOG__MINIMUMLEVEL__DEFAULT:      "Warning"
      MORPHIC_ENC_KEY_PRIMARY:             "TESTKEY:5E4FA583FDFFEEE0C89E91307A6AD56EDF2DADACDE5163C1485F3FBCC166B995"
      MORPHIC_ENC_KEY_ROLLOVER_1:          "ROLLOVER1:E9F45B9C675409B3980256D128EC90641EADF8D0E89DB8485B65B50B35717A94"
      MORPHICSETTINGS__SERVERURLPREFIX:    "http://localhost:5005"
      EMAILSETTINGS__SENDGRIDSETTINGS__APIKEY: ""
      EMAILSETTINGS__DISABLE":             "true"

